# ==================
# Tool configuration
# ==================

[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.pytest.ini_options]
minversion = "2.0"
addopts = "-rsfEX -p pytester --strict-markers --verbosity=3"
log_level = "DEBUG"
testpaths = ["*.py"]
xfail_strict = true
markers = [
]

[tool.ruff]
line-length = 120
extend-exclude = [
  "var",
]


# ===================
# Tasks configuration
# ===================

[tool.poe.tasks]
build = {cmd="python -m build"}
format = [
  {cmd="black ."},
  {cmd="isort ."},
]
lint = [
  {cmd="ruff ."},
  {cmd="black --check ."},
  {cmd="isort --check ."},
]
test = [
  {cmd="pytest"},
]
